# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dadeaea2738ebf70e64658c72fdb4d51441e0b3accb8264e73a7d469ee1b2aa9f5a3d0235a27289b448eb42d73096220db6cc4f5a4c9b109b40cd812b939447

test:
  secret_key_base: 6c565f2269b3a5507fa047b686de7ec0328d94771b7ee267a44f02cef36d075b684975dcb7f6695dfa1d7c6b9a8a6a459622eab7884093f0551be90420c85fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
